### ISSUE TITLE
/punishments is broken

### ISSUE THREAD

**Issue by BTKingly** [Warzone/TGM#680] opened 2020-08-31 05:06 UTC
**Describe the bug**
Instead of the normal view, this is what /punishments show. Also cannot revert punishments by clicking (/revert works fine, my bad).
![2020-08-31_01 03 02](https://user-images.githubusercontent.com/27841024/91684694-27f6ed00-eb26-11ea-9785-cb193e452e7f.png)

**Comment by JapaneseSquid** [comment] 2020-08-31 14:07
seems to be a warzone only issue, tank loaded the current version of tgm onto a server and it worked fine according to him

**Comment by Draem** [comment] 2020-09-01 16:28
the server restarted at some point and it seems to have fixed this
![https://i.imgur.com/5YnHpVu.png](https://i.imgur.com/5YnHpVu.png)
based on the fact that this command also used to have the same error. Other commands that I can test are fine now as well.

**Comment by BennyDoesTheStuff** [comment] 2020-09-01 16:29
Closing, reopen if we can reproduce and it continues to happen.

**Closed by BennyDoesTheStuff** 2020-09-01 16:29 UTC
Labels: bug
